export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  ORG_MANAGER = 'ORG_MANAGER',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
}

export enum OrgStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum MailStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_RESPONSE = 'AWAITING_RESPONSE',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  NO_REPLY = 'NO_REPLY',
}

export enum TeacherStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ON_LEAVE = 'ON_LEAVE',
  DELETED = 'DELETED',
}

export enum StudentStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ALUMNI = 'ALUMNI',
  DELETED = 'DELETED',
}

export enum OrganizationType {
  KINDERGARTEN = 'KINDERGARTEN',
  PRE_SCHOOL = 'PRE_SCHOOL',
  PRIMARY_SCHOOL = 'PRIMARY_SCHOOL',
  MIDDLE_SCHOOL = 'MIDDLE_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  COLLEGE = 'COLLEGE',
  UNIVERSITY = 'UNIVERSITY',
  VOCATIONAL_SCHOOL = 'VOCATIONAL_SCHOOL',
  INSTITUTE = 'INSTITUTE',
  ACADEMY = 'ACADEMY',
  TUTORING_CENTER = 'TUTORING_CENTER',
  ONLINE_SCHOOL = 'ONLINE_SCHOOL',
  OTHER = 'OTHER',
}

// ── Mail Categories (context-aware) ────────────────────────────────────────
export enum MailCategory {
  // Platform-level (messaging Super Admin / Platform Admin)
  ACCOUNT_STATUS = 'ACCOUNT_STATUS',
  BUG_REPORT = 'BUG_REPORT',
  FEATURE_REQUEST = 'FEATURE_REQUEST',
  BILLING = 'BILLING',
  PLATFORM_SUPPORT = 'PLATFORM_SUPPORT',
  // Platform → Org Admin
  ORG_COMPLIANCE = 'ORG_COMPLIANCE',
  ORG_ACCOUNT = 'ORG_ACCOUNT',
  PLATFORM_NOTICE = 'PLATFORM_NOTICE',
  // Org Admin/Manager → Staff
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',
  SCHEDULE_CHANGE = 'SCHEDULE_CHANGE',
  POLICY_UPDATE = 'POLICY_UPDATE',
  PERFORMANCE = 'PERFORMANCE',
  GENERAL_NOTICE = 'GENERAL_NOTICE',
  // Teacher → Manager/Teacher
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  RESOURCE_REQUEST = 'RESOURCE_REQUEST',
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  COLLABORATION = 'COLLABORATION',
  // Universal
  GENERAL_INQUIRY = 'GENERAL_INQUIRY',
  OTHER = 'OTHER',
}

export enum InsightTone {
  DEFAULT = 'default',
  INFO = 'info',
  SUCCESS = 'success',
  WARNING = 'warning',
  DANGER = 'danger',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  EXCUSED = 'EXCUSED',
}
